config/routes.rb
Rails.application.routes.draw do
  resources :ips, except: [:edit, :update], param: :ip_address, :constraints => {
    :ip_address => /\b(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\b/
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'ips#index'

end

app/models/ip.rb
class Ip < ApplicationRecord
  has_many :user_ips
  has_many :users, :through => :user_ips

  validates :ip_address, presence: true, format: {with: /\b(?:(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\b/, message: "format is invalid"}

  before_save :get_ip_info

  def get_ip_info
    ip_info = IpInfo.find(ip_address)
    ip_blocklist = IpBlocklist.find(ip_address)

    self.hostname = ip_info.hostname
    self.city = ip_info.city
    self.region = ip_info.region
    self.country = ip_info.country
    self.is_listed = ip_blocklist["is-listed"]
    self.is_malware = ip_blocklist["is-malware"]
    self.is_spyware = ip_blocklist["is-spyware"]
    self.is_hijacked = ip_blocklist["is-hijacked"]
    self.is_bot = ip_blocklist["is-bot"]
    self.is_spam_bot = ip_blocklist["is-spam-bot"]
    self.is_exploit_bot = ip_blocklist["is-exploit-bot"]
  end

end

app/controllers/ips_controller.rb
class IpsController < ApplicationController
  before_action :custom_authenticate_user
  before_action :set_ip, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /ips
  # GET /ips.json
  def index
    if @user.nil?
      @user = current_user
    end 
    @ips = @user.ips
  end

  # GET /ips/1
  # GET /ips/1.json
  def show
  end

  # GET /ips/new
  def new
    @ip = Ip.new
  end

  # POST /ips
  # POST /ips.json
  def create
    if @user.nil?
      @user = current_user
    end

    @ip = Ip.find_or_initialize_by(ip_address: ip_params[:ip_address])
    @ip.last_checked_at = DateTime.now.to_s

    respond_to do |format|
      if @ip.save
        @user_ip = UserIp.find_or_initialize_by(user_id: @user.id, ip_id: @ip.id)
        @user_ip.save
        format.html { redirect_to "/ips/#{@ip.ip_address}", notice: 'Ip was successfully added to your list.' }
        format.json { render :show, status: :created, location: "/ips/#{@ip.ip_address}" }
      else
        format.html { render :new }
        format.json { render json: wrong_format_json, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ips/1
  # DELETE /ips/1.json
  def destroy
    if @user.nil?
      @user = current_user
    end

    @user_ip = UserIp.find_by(user_id: @user.id, ip_id: @ip.id)
    @user_ip.destroy

    unless UserIp.where(ip_id: @ip.id).size > 0
      @ip.destroy
    end
    respond_to do |format|
      format.html { redirect_to ips_url, notice: 'Ip was successfully removed from your list.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ip
      if @user.blank?
        @user = current_user
      end
      @ip = @user.ips.find_by(ip_address: params[:ip_address])

      if @ip.nil?
        raise ActionController::RoutingError.new('Not Found')
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ip_params
      params.require(:ip).permit(:ip_address)
    end

    def custom_authenticate_user
      puts "Trying to authenticate user"
      puts "Content type: #{request.headers['Content-type']}, API-KEY: #{request.headers['x-api-key']}"

      respond_to do |format|

        format.html do
          puts "Processing as HTML"
          authenticate_user!
        end

        format.json do
          puts "Processing as json"
          unless request.headers["x-api-key"].blank?
            @user = User.find_by(api_key: request.headers["x-api-key"])
            if @user.nil?
              render json: unauthorized_json, status: :unauthorized
            end
          else
            render json: unauthorized_json, status: :unauthorized
          end
        end
      end
    end

    def unauthorized_json
      {
        "status": 401,
        "error": "Invalid API key"
      }
    end

    def wrong_format_json
      {
        "status": 400,
        "error": "Invalid IP address format"
      }
    end
  end

app/helpers/ips_helper.rb
module IpsHelper
end

app/views/ips/_form.html.haml
= form_for @ip do |f|
  - if @ip.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ip.errors.count, "error")} prohibited this ip from being saved:"
      %ul
        - @ip.errors.full_messages.each do |msg|
          %li= msg
  .row
    .field.left
      = f.label :ip_address
      = f.text_field :ip_address
  .actions
    = f.submit 'Save'

app/views/ips/edit.html.haml
%h1 Editing ip

= render 'form'

= link_to 'Show', @ip
\|
= link_to 'Back', ips_path

app/views/ips/index.html.haml
%h1 Listing ips

%table
  %thead
    %tr
      %th Ip address
      %th Last checked at
      %th Hostname
      %th Country
      %th Is listed
      %th
      %th

  %tbody
    - @ips.each do |ip|
      %tr
        %td= ip.ip_address
        %td= ip.last_checked_at
        %td= ip.hostname
        %td= ip.country
        %td= ip.is_listed
        %td= link_to 'Show', ip_path(ip.ip_address)
        %td= link_to 'Destroy', ip_path(ip.ip_address), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Ip', new_ip_path

app/views/ips/new.html.haml
%h1 New ip

= render 'form'

= link_to 'Back', ips_path

app/views/ips/show.html.haml
%p#notice= notice

%p
  %b Ip address:
  = @ip.ip_address
%p
  %b Last checked at:
  = @ip.last_checked_at
%p
  %b Hostname:
  = @ip.hostname
%p
  %b City:
  = @ip.city
%p
  %b Region:
  = @ip.region
%p
  %b Country:
  = @ip.country
%p
  %b Is listed:
  = @ip.is_listed
%p
  %b Is malware:
  = @ip.is_malware
%p
  %b Is spyware:
  = @ip.is_spyware
%p
  %b Is hijacked:
  = @ip.is_hijacked
%p
  %b Is bot:
  = @ip.is_bot
%p
  %b Is spam bot:
  = @ip.is_spam_bot
%p
  %b Is exploit bot:
  = @ip.is_exploit_bot

= link_to 'Back', ips_path